version: '3.7'

networks:
  ngface-net:
    driver: bridge

services:

  #####################################################################################
  postgres:
  #####################################################################################
    container_name: ngface-postgres
    image: postgres:10.13-alpine
    environment:
      - POSTGRES_PASSWORD=sa
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ngface-net



  #####################################################################################
  pgadmin:
  #####################################################################################
    container_name: ngface-pgadmin
    #image: dpage/pgadmin4
    image: thajeztah/pgadmin4
    #environment:
    #    - PGADMIN_DEFAULT_EMAIL=postgres
    #    - PGADMIN_DEFAULT_PASSWORD=sa
    ports:
      - "127.0.0.1:5400:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - ngface-net


  ######################################################################################
  #redis:
  ######################################################################################
  #  container_name: ngface-redis
  #  image: ngface-redis
  #  environment:
  #      - REDIS_PASSWORD=apfel
  #  ports:
  #      - 6379:6379
  #  networks:
  #    - ngface-net


volumes:
  postgres:
  pgadmin:
