version: '3.7'

networks:
  back-tier-net:
    driver: bridge
  db-net:
    driver: bridge
  monitoring:
    driver: bridge

services:

  #####################################################################################
  postgres:
  #####################################################################################
    container_name: ngface-postgres
    image: postgres:10.13-alpine
    environment:
      - POSTGRES_PASSWORD=sa
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back-tier-net
      - db-net


  #####################################################################################
  pgadmin:
  #####################################################################################
    container_name: ngface-pgadmin
    #image: dpage/pgadmin4
    image: thajeztah/pgadmin4
    #environment:
    #    - PGADMIN_DEFAULT_EMAIL=postgres
    #    - PGADMIN_DEFAULT_PASSWORD=sa
    ports:
      - "5400:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - db-net
    #logging:
    #    driver: none

volumes:
  postgres:
  pgadmin:
