#-----------------------------------------------------------------------------------------------------------------------
# datasource postgres on postgres
#-----------------------------------------------------------------------------------------------------------------------
datasource:
  addressdb:
    host: localhost
