#-----------------------------------------------------------------------------------------------------------------------
# Server settings
#-----------------------------------------------------------------------------------------------------------------------
server:
  fqdn: localhost
  port: 8400
  external-url: ""


#-----------------------------------------------------------------------------------------------------------------------
# datasource postgres on postgres
#-----------------------------------------------------------------------------------------------------------------------
datasource:
  addressdb:
    host: localhost
