version: '3.7'

networks:
  ngface-net:
    driver: bridge

services:

  #####################################################################################
  postgres:
  #####################################################################################
    container_name: ngface-postgres
    image: postgres:10.13-alpine
    environment:
      - POSTGRES_PASSWORD=sa
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ngface-net
    restart: unless-stopped


  #####################################################################################
  pgadmin:
  #####################################################################################
    container_name: ngface-pgadmin
    #image: dpage/pgadmin4
    image: thajeztah/pgadmin4
    #environment:
    #    - PGADMIN_DEFAULT_EMAIL=postgres
    #    - PGADMIN_DEFAULT_PASSWORD=sa
    ports:
      - "127.0.0.1:5400:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - ngface-net
    restart: unless-stopped


  #####################################################################################
  ngface-webservice:
  #####################################################################################
    container_name: ngface-webservice
    image: docker-registry:5000/ngface-webservice:2.4.0
    networks:
      - ngface-net
    restart: unless-stopped


  #####################################################################################
  ngface-app:
  #####################################################################################
    container_name: ngface-app
    image: docker-registry:5000/ngface-app:latest
    ports:
      - "127.0.0.1:16000:80"
    networks:
      - ngface-net
    restart: unless-stopped


volumes:
  postgres:
  pgadmin:
